Feature/add dropdown component
KonferCA/SPUR-Onboard pull request #11
Opened 2024-11-12 03:47 UTC by AmirAgassi

📂 **Add Dropdown Component**

🔍 **What's Included**
- Added `Dropdown` component.

📁 Files Affected:
- `src/components/Dropdown.tsx`
- `src/components/index.ts`
- `src/pages/Landing.tsx`

2024-11-13 02:22 UTC, juancwu requested changes

2024-11-13 02:22 UTC, juancwu commented on src/components/Dropdown.tsx
> +        <div className="w-[400px]">
We should use a max width instead to allow the component to shrink

2024-11-15 06:15 UTC, aidantrabs commented
conflicts!!!

2024-11-15 06:18 UTC, juancwu approved these changes

2024-11-15 06:25 UTC, merged