Feature/add text input component
KonferCA/SPUR-Onboard pull request #12
Opened 2024-11-12 03:51 UTC by AmirAgassi

📂 **Add Text Input Component**

🔍 **What's Included**
- Added `TextInput` component.

📁 Files Affected:
- `src/components/TextInput.tsx`
- `src/components/index.ts`
- `src/pages/Landing.tsx`

2024-11-13 02:19 UTC, juancwu requested changes

2024-11-13 02:19 UTC, juancwu commented on src/components/TextInput.tsx
> +            <div className="w-[400px]">
I dont think we should set a fixed size of any component, but instead use a max width so that it can still shrink when needed.

2024-11-13 02:19 UTC, juancwu commented on src/components/TextInput.tsx
Any reason why for not using the headless ui input? https://headlessui.com/react/input#examples

It adds some features such as focusing when clicking on the label and formatting when there is description and label etc

2024-11-15 06:15 UTC, aidantrabs commented
conflicts!!!

2024-11-15 06:17 UTC, juancwu approved these changes
lgtm :+1:

2024-11-15 06:28 UTC, merged