Feature/add button component
KonferCA/SPUR-Onboard pull request #13
Opened 2024-11-12 04:14 UTC by AmirAgassi

🔘 **Add Button Component**

🔍 **What's Included**
- Add `Button` component.

📁 Files Affected:
- `src/components/Button.tsx`
- `src/components/index.ts`
- `src/pages/Landing.tsx`

2024-11-13 02:12 UTC, juancwu approved these changes
ltgm 👍

2024-11-13 02:12 UTC, juancwu commented on src/components/Button.tsx
> +        };
I can see how this pattern of assigning different classes will be in almost every component, we can implement https://cva.style/docs/getting-started/installation later on to make this cleaner and easier to manage.

2024-11-13 02:16 UTC, AmirAgassi commented on src/components/Button.tsx
> +        };
> I can see how this pattern of assigning different classes will be in almost every component, we can implement https://cva.style/docs/getting-started/installation later on to make this cleaner and easier to manage.

How have I never heard of this?? For sure

2024-11-15 05:22 UTC, SherRao requested changes
these are shit

2024-11-15 05:23 UTC, AmirAgassi commented
> these are shit

ur fired buddy

2024-11-15 05:27 UTC, merged