Add team endpoints
KonferCA/SPUR-Onboard pull request #289
Opened 2024-12-23 04:06 UTC by AmirAgassi

## Description
Adds new endpoints to manage team members for companies, including creating, retrieving, updating, and deleting team members

## Linked Issues
- #193 
- #194 
- #195 
- #196 
- #197 

## Testing
- `backend/internal/tests/team_test.go`

## Checklist
Before opening this PR, make sure the PR:
- [ ] Has an **assignee or group of assignees**.
- [ ] Has a **reviewer or a group of reviewers**.
- [ ] Is **labelled properly**.
- [ ] Has the **SPUR project assigned to it**.
- [ ] Has an **assigned milestone**.

Additionally, make sure that:
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2024-12-23 04:53 UTC, aidantrabs requested changes
new common utils needs to be merged in, a lot of functions need to be updated (example: instead of doing bind and validate seperately, we have a joint helper, also error handling is different now too)

2024-12-23 20:07 UTC, juancwu commented on backend/.sqlc/queries/team_members.sql
> +    id, company_id, first_name, last_name,
There is no need to include the id in here, you can let postgres handle it since it has internal collision resolution.

2024-12-23 21:01 UTC, aidantrabs approved these changes, later dismissed
lgtm

2024-12-26 22:49 UTC, juancwu commented on backend/internal/v1/v1_teams/members.go
> +		return err
Should use the fail function instead so that it is wrapped in an APIError. There are multiple instances in all handlers.

2024-12-26 22:49 UTC, juancwu commented on backend/internal/v1/v1_teams/members.go
> +func (h *Handler) validateCompanyAccess(c echo.Context, companyID string, requireOwner bool) error {
Can you add some docs that says that this function allows owner and non-owners based on the requireOwner boolean?

2024-12-27 23:05 UTC, juancwu approved these changes
lgtm

2024-12-27 23:40 UTC, merged